### PR TITLE
deps: update to CloudEvents 4.0.0 and some linting

### PR DESCRIPTION
**Pull request by lance**
Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by lholmquist** [comment]
4.0.1 was just released if you want to update to that

**Comment by lance** [comment]
@lholmquist actually - I found a bug in cloudevents sdk and will submit a PR today. Then update to 4.0.2 :wink:

**Comment by lance** [comment]
https://github.com/cloudevents/sdk-javascript/pull/394

**Review by lkingland — APPROVED** [review]
Looks good from where I'm sitting.

**Pull request merged**
