### PR TITLE
feat: support binary data in cloudevents

### PR DESCRIPTION
**Pull request by lance**
Depends on: https://github.com/cloudevents/sdk-javascript/pull/468
Fixes: https://github.com/boson-project/faas-js-runtime/issues/64

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by lance** [comment]
Needs: https://github.com/cloudevents/sdk-javascript/pull/466

**Comment by matejvasek** [comment]
@lance is knative.gz used somewhere?

**Comment by lance** [comment]
> @lance is knative.gz used somewhere?

@matejvasek I had a test for it which was failing. I forgot to remove the fixture file. I'm digging into why it's failing. It looks like it's [logic in the test framework here](https://github.com/visionmedia/superagent/blob/84206c75214e20bbc688d0645880696ecd773c27/src/node/index.js#L1082-L1084
) that converts the gzip binary data to string. So, I __think__ that gzip should work in practice, just not in tests.

**Review by matejvasek — APPROVED** [review]

**Pull request merged**
