### PR TITLE
lib(deps): update to cloudevents 3.0.x

### PR DESCRIPTION
**Pull request by lance**
This commit updates the cloudevent-sdk to use the newly named cloudevents
module at version 3.0.1.

### CODE REVIEW

**Comment by lance** [comment]
@lholmquist if you wouldn't mind taking a look at this. I wonder if we need to expose the `cloudevents` constants as they used to be. See: https://github.com/boson-project/faas-js-runtime/pull/45/files#diff-f10de3b2ee2344fc6bb34d7f0d6515d2R1

**Comment by matejvasek** [comment]
@lance  /LGTM, but what about the two previous PR generated by bot?

**Comment by lholmquist** [comment]
@lance we could do that.   What you are doing works,  but it doesn't seem ideal

**Comment by lance** [comment]
> what about the two previous PR generated by bot?

Yes, these should land.

**Pull request merged**
